# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(default=b'', max_length=20)),
                ('about', models.TextField(blank=True, default=b'', null=True)),
                ('content_id', models.CharField(blank=True, max_length=2, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_contacted', models.DateTimeField(null=True)),
                ('last_modified', models.DateTimeField(null=True)),
            ],
        ),
    ]
